services:
  db:
    image: postgres:latest
    container_name: tareas-app-postgres
    mem_limit: 512m
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tareas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    restart: no
  php:
    #image: php:8.1-apache
    mem_limit: 512m
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tareas-app-php
    ports:
      - "8080:80"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
    networks:
      - backend
    restart: no

  jasperreports:
    image: bitnami/jasperreports:latest
    environment:
      JASPERREPORTS_DATABASE_HOST: tareas-app-postgres
      JASPERREPORTS_DATABASE_PORT_NUMBER: 5432
      JASPERREPORTS_DATABASE_NAME: tareas
      JASPERREPORTS_DATABASE_USER: postgres
      JASPERREPORTS_DATABASE_PASSWORD: postgres
      JASPERREPORTS_USERNAME: admin
      JASPERREPORTS_PASSWORD: admin
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  postgres_data:
networks:
  backend:
    driver: bridge
