services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tareas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    #restart: always
  php:
    #image: php:8.1-apache
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tareas-app-php
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
    networks:
      - backend
    #restart: always


volumes:
  postgres_data:
networks:
  backend:
    driver: bridge
