services:
  db:
    image: postgres:latest
    container_name: tareas-app-postgres
    mem_limit: 512m
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tareas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    restart: no
  php:
    image: php:8.1-apache
    mem_limit: 512m
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tareas-app-php
    ports:
      - "8080:80"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
    networks:
      - backend
    restart: no

volumes:
  postgres_data:
networks:
  backend:
    driver: bridge
